baseURL = "https://beadenkopf.com/"
languageCode = "en-us"
title = "bdnkpf"
theme = "pixls_theme"

HUGO_CANONIFYURLS=false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
[[menu.main]]
    identifier = 'home'
    name = 'Home'
    url = '/'
    weight = 1
[[menu.main]]
    identifier = 'work'
    name = 'Work'
    url = '/work/'
    weight = 10

[[menu.workCategories]]
    identifier = 'bike'
    name = 'Bike'
    url = '/work/bike'
    weight = 10
[[menu.workCategories]]
    identifier = 'keyboard'
    name = 'Keyboard'
    url = '/work/keyboard'
    weight = 20


[params]
