baseURL = "http://example.org/"
languageCode = "en-us"
title = "bdnkpf"

[menu]
[[menu.main]]
    identifier = 'home'
    name = 'Home'
    url = '/'
    weight = 0
[[menu.main]]
    identifier = 'work'
    name = 'Work'
    url = '/work'
    weight = 10

[[menu.workCategories]]
    identifier = 'bike'
    name = 'Bike'
    url = '/work/bike'
    weight = 10
[[menu.workCategories]]
    identifier = 'keyboard'
    name = 'Keyboard'
    url = '/work/keyboard'
    weight = 20